# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'backup',
            },
        ),
        migrations.CreateModel(
            name='Battalion',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='Name of Battalion')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
            ],
            options={
                'db_table': 'battalions',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('repr', models.CharField(max_length=250, verbose_name='id of unit')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Geospace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'geospaces',
            },
        ),
        migrations.CreateModel(
            name='Intrusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_datetime', models.DateTimeField()),
                ('verified_datetime', models.DateTimeField(blank=True, null=True)),
                ('neutralized_datetime', models.DateTimeField(blank=True, null=True)),
                ('non_human_intrusion_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField()),
            ],
            options={
                'db_table': 'intrusions',
            },
        ),
        migrations.CreateModel(
            name='Morcha',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='name of morcha')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('geospace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archives.Geospace')),
            ],
            options={
                'db_table': 'morchas',
            },
        ),
        migrations.CreateModel(
            name='Offline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('morcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offlinemorcha', to='archives.Morcha')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offlineunit', to='archives.Device')),
            ],
            options={
                'db_table': 'offline',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=250, verbose_name='name of post')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('battalion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='archives.Battalion')),
                ('geospace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archives.Geospace')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Weaksignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('morcha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaksignalmorcha', to='archives.Morcha')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weksignalunit', to='archives.Device')),
            ],
            options={
                'db_table': 'weaksignal',
            },
        ),
        migrations.AddField(
            model_name='morcha',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morchas', to='archives.Post'),
        ),
        migrations.AddField(
            model_name='morcha',
            name='qrt_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrt', to='archives.Device'),
        ),
        migrations.AddField(
            model_name='morcha',
            name='units',
            field=models.ManyToManyField(null=True, related_name='units', to='archives.Device'),
        ),
        migrations.AddField(
            model_name='intrusion',
            name='morcha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morcha', to='archives.Morcha'),
        ),
        migrations.AddField(
            model_name='battalion',
            name='geospace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='archives.Geospace'),
        ),
        migrations.AddField(
            model_name='backup',
            name='morcha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morchaevent', to='archives.Morcha'),
        ),
        migrations.AddField(
            model_name='backup',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitevent', to='archives.Device'),
        ),
    ]
