# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morcha',
            name='qrt_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrt', to='archives.Device'),
        ),
    ]
