# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20170218_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaksignal',
            name='morcha',
        ),
        migrations.RemoveField(
            model_name='weaksignal',
            name='unit',
        ),
    ]
