# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20170218_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaksignal',
            name='morcha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weaksignalmorcha', to='archives.Morcha'),
        ),
        migrations.AddField(
            model_name='weaksignal',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weksignalunit', to='archives.Device'),
        ),
    ]
