# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_auto_20170218_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offline',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weaksignal',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
