# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_remove_weaksignal_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offline',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
